#!/bin/bash
######################################
# al_eo lingvo [dosiero]*
######################################

if [ $# -lt 1 ] ; then
  echo "pas assez d'arguments."
  exit
fi

lang0=$1
laborhejmo=`grep "laborhejmo:" _config.yml|awk '{print $2;}'`
if [ $laborhejmo = "true" ] ; then
  LABORHEJMO=$lang0
  RAD_DOS=".."
else
  LABORHEJMO="."
  RAD_DOS="."
fi
echo LABORHEJMO=$LABORHEJMO args="$@"

BASEDIR=`dirname $0`
if [ ! -d "$BASEDIR"/../../$LABORHEJMO ] ; then
  echo "chemin introuvable."
  exit
fi
cd "$BASEDIR"/../../$LABORHEJMO

if [ $# -gt 1 ] ; then 
  shift
  echo "$@"
else
  find _posts *.md _data/site-translations.yml -type f -name "*.md" -o -name "*.yml"| egrep -v "/_drafts/|.backup$|.swp$"
fi | while read FIC
do
  EXT="${FIC##*.}"
  case "$EXT" in
	yml)
	  OPTIONS="-f yaml" 
          ;;
	*)
	  OPTIONS="-f text --option markdown -o neverwrap" 
          ;;
  esac
  # détruire le fichier eo --> langue s'il existe pour éviter la retraduction eo-->langue
  if [ -f "${RAD_DOS}/_locale/${lang0}/${FIC}.po" ]
  then
    rm -f "${RAD_DOS}/_locale/${lang0}/${FIC}.po"
    if [ -f "${RAD_DOS}/eo/${FIC}" -a ! -f "${RAD_DOS}/_locale/eo/${FIC}.po" ]
    then
      # si ce fichier est une bonne traduction, il faut la récupérer en générant le .po
      po4a-gettextize -m "${FIC}" -M "UTF-8" $OPTIONS -l "${RAD_DOS}/eo/${FIC}" -L "UTF-8" --po "${RAD_DOS}/_locale/eo/${FIC}.po" 
      rm -f gettextization.failed.po "${RAD_DOS}/eo/${FIC}"
    fi
  fi

  if [ ! -f "${RAD_DOS}/_locale/${lang0}/${FIC}.pot" ]
  then
    po4a-gettextize -m "${FIC}" --master-charset "UTF-8" $OPTIONS --po "${RAD_DOS}/_locale/${lang0}/${FIC}.pot" 
  else
    if [ "${RAD_DOS}/_locale/${lang0}/${FIC}.pot" -ot "${FIC}" ]
    then
      po4a-updatepo --wrap-po no -m "${FIC}" --master-charset "UTF-8" $OPTIONS --po "${RAD_DOS}/_locale/${lang0}/${FIC}.pot" 
    fi
  fi
  for lang in eo
  #for lang in `grep "^..:$" ${RAD_DOS}/_data/languages.yml|sed "s/:$//"|grep -v eo`
  do
    if [ ! -f "${RAD_DOS}/_locale/${lang}/${FIC}.po" -a -f "${RAD_DOS}/${lang}/${FIC}" ]
    then
      continue;
    fi
    if [ ! -f "${RAD_DOS}/_locale/${lang}/${FIC}.po" ]
    then
      echo "krei traduko ${FIC} al ${lang}"
      cat "${RAD_DOS}/_locale/${lang0}/${FIC}.pot"|sed "s/^\"Language: \\\n\"/\"Language: "${lang}"\\\n\"/" > "${RAD_DOS}/_locale/${lang}/${FIC}.po"
    fi
    if [ "${RAD_DOS}/_locale/${lang}/${FIC}.po" -ot "${RAD_DOS}/_locale/${lang0}/${FIC}.pot" ]
    then
      echo "ĝisdatigi traduko ${FIC} al ${lang}"
      po4a-updatepo --msgmerge-opt --no-fuzzy-matching --wrap-po no -m "${FIC}" --master-charset "UTF-8" $OPTIONS --po "${RAD_DOS}/_locale/${lang}/${FIC}.po"
    fi
    cat "${RAD_DOS}/_locale/${lang}/${FIC}.po"|gawk -v BASEDIR=${RAD_DOS}/$BASEDIR -v src=${lang0} -v dst=eo -f ${RAD_DOS}/_scripts/lib/traduki_po.awk > "${RAD_DOS}/_locale/${lang}/${FIC}.po.nova"
    if diff "${RAD_DOS}/_locale/${lang}/${FIC}.po.nova" "${RAD_DOS}/_locale/${lang}/${FIC}.po" >/dev/null
    then
      rm "${RAD_DOS}/_locale/${lang}/${FIC}.po.nova"
      touch "${RAD_DOS}/_locale/${lang}/${FIC}.po"
    else
      echo ĝisdatigi "_locale/${lang}/${FIC}.po"
      mv "${RAD_DOS}/_locale/${lang}/${FIC}.po.nova" "${RAD_DOS}/_locale/${lang}/${FIC}.po"
      ## forigi neuzatajn frazojn 
      msgattrib --no-obsolete -o "${RAD_DOS}/_locale/${lang}/${FIC}.po" "${RAD_DOS}/_locale/${lang}/${FIC}.po"
    fi
    if [ "${RAD_DOS}/${lang}/${FIC}" -ot "${RAD_DOS}/_locale/${lang}/${FIC}.po" ]
    then
      echo "tradukante ${FIC} al ${lang}"
      #grep -v "^#, fuzzy" ${RAD_DOS}/_locale/${lang}/${FIC}.po >${RAD_DOS}/_locale/temp$$.po
      cat "${RAD_DOS}/_locale/${lang}/${FIC}.po"|sed "s/^#, fuzzy/#/" >${RAD_DOS}/_locale/temp$$.po
      po4a-translate $OPTIONS -m "${FIC}" --master-charset "UTF-8"  --po ${RAD_DOS}/_locale/temp$$.po --localized "${RAD_DOS}/${lang}/${FIC}" --localized-charset "UTF-8" -k 0
      if egrep -m 1 "^#.*, fuzzy" "${RAD_DOS}/_locale/${lang}/${FIC}.po" >/dev/null
      then
       true
      else
       sed -i "s/^lang-niv: auto$/lang-niv: homa/" "${RAD_DOS}/${lang}/${FIC}"
      fi
      rm ${RAD_DOS}/_locale/temp$$.po
    fi
  done
done




