#!/bin/bash

BASEDIR=`dirname $0`
cd "$BASEDIR"
cd ..

echo "ĉi tiu skripto estas uzata por administri po-dosierojn en malklara stato."

if [ $# -ge 1 ]
then
  LINGVO=$1
else
  read -p "Kiu cellingvo ? " LINGVO
fi

if [ ! -d _locale/$LINGVO ]
then
  echo "Pardonu, ne troviĝis $ LINGVO."
  sleep 2
  exit
fi

if [ $# -ge 2 ]
then
  ACTION=$2
else
  read -p "Kia ago ? l=ls, z=zip, v=malfermi per virtaal, p=malfermi per poedit : " ACTION
fi

case $ACTION in
  l)
    find _locale/$LINGVO -type f -name "*.po" -exec grep -l fuzzy {} \;
    ;;
  p)
    cd _locale/$LINGVO
    poedit `find . -type f -name "*.po" -exec grep -l fuzzy {} \;`
    ;;
  v)
    cd _locale/$LINGVO
    for x in `find . -type f -name "*.po" -exec grep -l fuzzy {} \;`;
     do
      virtaal "$x" &
     done
    ;;
  z)
    cd _locale/$LINGVO
    find . -type f -name "*.po" -exec grep -l fuzzy {} \;|zip ../$LINGVO -@
    sleep 2
    ;;
  *)
    echo "pardonu, ${ACTION} ago ne rekonita."
    sleep 2
    ;;
esac

