#!/bin/bash

export TEXTDOMAINDIR=$(dirname $(readlink -f $0))/locale
export TEXTDOMAIN=$(basename $0)
. gettext.sh


BASEDIR=$(dirname $(readlink -f $0))
cd "$BASEDIR"
cd ..

trad()
{
MSG0="$1"
MSG1=`eval_gettext "$1"`
if [ "$MSG1" == "$MSG0" ] ; then
  L2=$(echo $LANG|awk '{print substr($1,1,2);}' )
  MSG2=`$BASEDIR/lib/traduko.sh eo $L2 "$1"`
  if [ "MSG2" != "" ] ; then
    MSG1="$MSG2"
  fi
fi
echo "$MSG1"
}

echo "`trad 'ĉi tiu skripto estas uzata por administri po-dosierojn en malklara stato.'`"

if [ $# -ge 1 ]
then
  LINGVO=$1
else
  read -p "`trad 'Kiu cellingvo ?'` " LINGVO
fi

if [ ! -d _locale/$LINGVO ]
then
  echo "`trad 'Pardonu, ne troviĝis'` $LINGVO."
  sleep 2
  exit
fi

if [ $# -ge 2 ]
then
  ACTION=$2
else
  read -p "`trad 'Kia ago ?'` l=ls, z=zip, v=virtaal, p=poedit : " ACTION
fi

case $ACTION in
  l)
    find _locale/$LINGVO -type f -name "*.po" -exec grep -l fuzzy {} \;
    ;;
  p)
    cd _locale/$LINGVO
    poedit `find . -type f -name "*.po" -exec grep -l fuzzy {} \;`
    ;;
  v)
    cd _locale/$LINGVO
    for x in `find . -type f -name "*.po" -exec grep -l fuzzy {} \;`;
     do
      virtaal "$x" &
     done
    ;;
  z)
    cd _locale/$LINGVO
    find . -type f -name "*.po" -exec grep -l fuzzy {} \;|zip ../$LINGVO -@
    sleep 2
    ;;
  *)
    echo "`trad 'pardonu,'` ${ACTION} `trad 'ago ne rekonita.'`"
    sleep 2
    ;;
esac

read -p "`trad 'Premu enigoklavon.'` " 
